apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - configmap.yaml
patches:
  - path: patch-deployment-environnement.yaml
  - path: patch-deployment-replicas.yaml
  - path: patch-deployment-ressources.yaml
  - path: patch-deployment-maxunavailable.yaml
images:
  - name: ghcr.io/swanronco/frontend-nextjs-graphql
    newTag: latest
