apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nextjs-graphql
  namespace: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend-nextjs-graphql
          env:
            - name: NODE_ENV
              value: "production"
