apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-quota
  namespace: frontend
spec:
  hard:
    requests.cpu: "800m"
    requests.memory: "800Mi"
    limits.cpu: "1200m"
    limits.memory: "1600Mi"
    pods: "10"
